project:
  type: website
  output-dir: docs

format:
  html:
    theme: cosmo
    toc: true
    math: mathjax

website:
  title: "Math 151 - Calculus II"
  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Syllabus"
        file: syllabus/syllabus.qmd
      - text: "Grading Guide"
        file: grading/grading-guide.qmd