project:
  type: website
  output-dir: docs
  render:
    - "**/*.qmd"
    - "!syllabus/**"

website:
  title: "Math 151 - Calculus II"
  sidebar:
    contents:
      - text: "Home"
        file: index.qmd
      - text: "Course Grading"
        file: grading/course-grading.qmd
      - text: "Learning Targets"
        file: grading/course-learning-targets.qmd
      - section: "Class Material"
        contents:

          - file: classes/01/slides.qmd
          - file: classes/02/slides.qmd
          - file: classes/03/slides.qmd
          - file: classes/04/slides.qmd
          - file: classes/05/slides.qmd
          - file: classes/06/slides.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    html-math-method: mathjax

  pdf:
    toc: true
    number-sections: false