---
title: "Math 151 Syllabus"
format:
  html:
    toc: true
    math: mathjax
  pdf: default
---

# Math 151: Calculus II

## Math 151 Specific Information
 
**Professor:** Geoffrey Buhl  
**Email:** geoffrey.buhl@csuci.edu  
**Phone:** 805-437-3122  
**Office:** 2324 Marin Hall  
**Office hours:** MW 9:00–10:00am or by appointment  
**Course meetings:** Tuesday and Thursday, 10:00–11:50am  
**Course textbook:** [OpexStax Calculus Volume 2](https://openstax.org/details/books/calculus-volume-2)  
**Course website:** CI Learn  



### Why I like this course

Calculus II is a course where we deepen our understanding of integration, infinite series, and the powerful ideas that connect them. You will be challenged to think carefully, reason precisely, and build on the foundations you’ve already developed in Calculus I. I encourage you to stay curious, ask questions, and engage fully as we explore the elegance and utility of calculus together.

### Course Description

Prerequisite: MATH 150

Topics include: differentiation, integration, sequences, infinite series, and power series.

### How to contact me

The best way to get in touch with me is in-person or by email.  In general, if you have any difficulties with the material, schedule, or anything else, get in touch with me. I'm here to help, and it's much easier to help if you are proactive.  If my office hours don't work for you, email me and we can work out a time to me in-person or via Zoom.

### Student Learning Outcomes

- Design mathematical models and work with functions
- Compute integrals, areas, volumes, surface areas
- Analyze various representations of functions and use them to solve problems
- Apply modern software to solve problems
- Apply integral optimization techniques
- Apply sequences, series and power series to solve problems
- Explain, using proper terminology, ideas of calculus and solve computational problems using good technique.
- Express ideas of Calculus in oral and written form.

### Course Workload

This is a 3 credit hour course, which means that students should be prepared to spend 9 hours a week on work related to this class outside of class.  Spending time throughout the week working on homework is critical for a successful learning experience.

### Student Evaluation Structure

In this course, Prof. Buhl uses specification grading, which has also been known as mastery grading. Assignments and assessments are graded based on whether or not they provide Prof. Buhl evidence that you, the student, have learned the material. The more course material you demonstate that you have learned, the higher your grade in
the course.m. Please see the Course Grading document on CI Learn for complete details on how your grade is determined.

### Educational Opportunities

If you have special educational opportunities, like traveling for a conference, going to Santa Rosa Island, participating in an academic competition that would cause you to miss class, *I strongly encourage you to take part in these special opportunities.*  Please let me know in advance, and we can work together on a plan to  address any missed learning.

### Collaboration Policy

Working in groups on the homework assignment is strongly encouraged.  However each person should individually write up their solutions, relying only on their notes about the problem.  On each homework assignment, please indicate which students you worked with.  An important part of mathematical culture and work is acknowledging the people that helped you understand and solve a problem.

### Additional Resources

**Office hours** is a time when you can come to my office and ask me questions about course material.  Students who make use of office hours tend to do better in college courses. You are encouraged to make early and regular use of **campus tutors** in the LRC. For campus tutoring locations, subjects and hours, use [this link](http://go.csuci.edu/tutoring).

### Course Outline

The course divides into three sections:

1. Techniques of integration and their applications (weeks 1-7),
2. Sequences and series of real numbers (weeks 8-13), and
3. Power series and their convergence (weeks 14-15).

Two themes pervade the course: what to do when the Fundamental Theorem of
Calculus does or does not work; and that limits can turn approximations into equalities.

### Class Schedule

| Week | Date | Chapter | Notes |
|:----:|:----:|:-------:|-------|
| 1 | Aug 25 | 1.1, 1.2, 1.3 |   |
| 1 | Aug 27 | 1.3, 1.4 |  |
| 2 | Sep 1 | 1.5, 1.6, 1.7 |  |
| 2 | Sep 3 | 2.1, 2.2 |  |
| 3 | Sep 8 | 2.2 | |
| 3 | Sep 10 | 2.3 |   |
| 4 | Sep 15 |  | Target Learning Assessment **A1**, **A2** |
| 4 | Sep 17 | 2.4 |   |
| 5 | Sep 22 | 2.5, 2.6 |  |
| 5 | Sep 24 | 2.7, 2.8  |   |
| 6 | Sep 29 | 2.5 | Target Learning Assessment **A3**, **A4** \*, **A5** \* |
| 6 | Oct 1 |  3.1, 3.4 |   |
| 7 | Oct 6 | 3.2, 3.3 |  |
| 7 | Oct 8 |  |  3.7 |
| 8 | Oct 13 |  | Target Learning Assessment **I1**, **I2**, **I4** \* |
| 8 | Oct 15 | 3.6 |   |
| 9 | Oct 20 | 3.6 |  |
| 9 | Oct 22 |  5.1 |   |
| 10 | Oct 27 |  | Target Learning Assessment **I3**, **N1**, **N2** |
| 10 | Oct 29 | 5.2 |   |
| 11 | Nov 3 | 5.3, 5.4 |  |
| 11 | Nov 5 | 5.5, 5.6 |  |
| 12 | Nov 10 |   | Target Learning Assessment **S1**, **S2**, **S3** |
| 12 | Nov 12 | 6.1 |   |
| 13 | Nov 17 | 6.2 | |
| 13 | Nov 19 | 6.3 |   |
| 14 | Nov 24 |  |  Target Learning Assessment **P1**, **P2** \*, **student choice** |
| 14 | Nov 27 |  | **Thanksgiving** - Campus Closed  |
| 15 | Dec 1 | 6.4 |  |
| 15 | Dec 3 |  |  Target Learning Assessment Lab |
|  | Dec 10 |  | **Final Exam** 8:00AM - 10:00AM |

## CSU Channel Islands Information

### Degree Planning

During Week 3 of classes of each semester, you are asked to update your information in the degree planner. The degree planner is a useful tool to help you stay on track toward achieving your goal of graduation. Students can learn how to update the degree planner using information provided here.

### In Case of Disruption

Wildfires and COVID are example of big disruptions that affect us all. There are smaller ones, like the class I wasn't able to teach because my second child was being born or when students have to help their family members.  Events big and small can affect our ability to be in class, but the goal to make sure learning keeps happening.

So, yes disruptions big and small happen! A disruption means you, me, or all of us cannot participate in 'class as usual' for a reason we could not predict at the beginning of the semester.  After COVID-19, we are well aware that disruption can happen fast. While we hope to avoid any closures due to COVID related reasons, let's face it, disruption happens every semester. You may get sick, I may get sick, or campus may close due to a wildfire - this is California after all. Life happens!  Our goal as a learning community is to do our best to keep teaching and learning with as little interruption as possible. This page explains what you can expect from me and what I expect from you when facing disruption - small or big! 

**If I am out**: If for whatever reason I am unable to be on campus, I will move lectures to a zoom format, which will be communicated by the announcement in this course.  I will record these lecture and post them as well.

**If you are out**: Be proactive and communicate!  I will always work with you to figure out how to help you keep learning!  I have old lectures and notes that are recorded that I can share, if that is what is needed.  If you just need a little extra time to get something done, let me know, I will always grant you a few more days on assignments.

**If campus closes**: If all of campus closes, which has happened at least once over the last three or more academic years,  we will move to Zoom classes which I will also record and post in the pages for each class.  I will communicate changes to the course schedule or other changes by using announcements in CILearn. More details can be found on the "Disruption Plan" page for this course on CI Learn.

### Important note about a possible work stoppage during the semester

The California Faculty Association (the union that represents all CSU faculty, including lecturer faculty, tenure-line faculty, coaches, counselors, and librarians) is in the midst of a difficult contract dispute with the CSU system-wide administration. In response to the CSU management's stance, it is possible that the faculty union will call a strike or other work stoppage this term. I promise to inform the class as soon as possible of any disruption to our class meeting schedule.

### Accommodations

If you are a student with a disability requesting reasonable accommodations in this course, please visit Disability Accommodations and Support Services (DASS) located on the second floor of Arroyo Hall, or call 805-437-3331. All requests for reasonable accommodations require registration with DASS in advance of need. You can apply for DASS services here. Faculty, students and DASS will work together regarding classroom accommodations. You are encouraged to discuss approved accommodations with your faculty.

### Civil Discourse Statement

All students, staff and faculty on our campus are expected to join in making our campus a safe space for communication and civil discourse. If you are experiencing discomfort related to the language you are hearing or seeing on campus (in or out of classes), please talk with a trusted faculty or staff member. Similarly, please consider whether the language that you are using (in person or on Canvas) respects the rights of others to engage in informed discourse and express a diversity of opinions freely and in a civil manner (language from Academic Senate Resolution SR 16-01, Commitment to Equity, Inclusion, and Civil Discourse within our Diverse Campus Community).
 
### Basic Needs at CI

If you face challenges securing food, housing, or other basic needs, you are not alone, and CSUCI wants to help during this time of crisis. One helpful resource is the community of staff available through the Basic Needs Program (BNP) located on the first floor of Arroyo Hall, Room 114. Students can call 805-437-2067, email basicneeds@csuci.edu, or drop in during open hours and talk with a BNP student assistant or professional staff member for resources, ideas, and strategies connected to basic needs challenges. Students can complete a referral form to request services for themselves or others by going to www.csuci.edu/basicneeds. The BNP is known for the Dolphin Pantry located at Arroyo Hall 114, but there are other resources available and staff who can help you work through housing insecurity or displacement as well as financial insecurity. Undergraduate students living in California are especially encouraged to explore CalFresh (grocery money each month for eligible students) as a resource. Domestic undergraduate students living in California are likely to be eligible for CalFresh and BNP staff are skilled with helping students navigate this process.

### Counseling and Psychological Services (CAPS)

CAPS is pleased to provide a wide range of services to assist students in achieving their academic and personal goals.  Services include confidential short-term counseling, crisis intervention, psychiatric consultation, and 24/7 phone counseling.  CAPS is located in Bell Tower East, 1867 and can be reached at 805-437-2088 (select option 1 on voicemail for 24/7 phone counseling); you can also email us at caps@csuci.edu or visit our website at https://www.csuci.edu/caps. 

### Academic Honesty

*By enrolling at CSU Channel Islands, students are responsible for upholding the University's policies and the Student Conduct Code. Academic integrity and scholarship are values of the institution that ensure respect for the academic reputation of the University, students, faculty, and staff. Cheating, plagiarism, unauthorized collaboration with another student, knowingly furnishing false information to the University, buying, selling or stealing any material for an examination, or substituting for another person may be considered violations of the Student Conduct Code (located at http://www.csuci.edu/campuslife/student-conduct/academic-dishonesty.htm). If a student is found responsible for committing an act of academic dishonesty in this course, the student may receive academic penalties including a failing grade on an assignment or in the course, and a disciplinary referral will be made and submitted to the Dean of Students office. For additional information, please see the faculty Academic Senate Policy on Academic Dishonesty, also in the CI Catalog. Please ask about my expectations regarding academic dishonesty in this course if they are unclear.*

Basically what this boils down to is: the work that you submit for credit should be your own work and reflect your understanding of the course material.  Group work, collaborations, and the free exchange of ideas are fundamental aspects of an academic environment.  I encourage you all to talk and work with others in the class, as it will enhance your understanding of the material.  You must write up your assignment individually and explain solutions in your own words. It is also important to cite resources you used in work, these may include other students, books, websites, and instructors.

There is a distinction between collaboration and copying.  Collaboration is encouraged; copying solutions or assignments is not allowed.  If I find copying of solutions on an assignment it will result in a score of 0 on that assignment.  Multiple instances of academic dishonesty will be formally documented with the University.

**Academic Honesty and Generative AI:** I have begun to notice students submitting work generated by AI.  This is copying.  If I suspect AI has been used on an assignment, I will assign a score of 0, but you can present your work in office hours or by appointment to receive credit.

### Disclaimer on syllabus changes

Information on this syllabus is subject to change. I will make such changes known in class and on CI Learn.


