---
title: "Mass, Density, Force, and Work"

format:
  revealjs:
    theme: solarized
    slide-number: true
    include-after-body:
      text: |
        <script>
        (function useMathJaxSVG() {
          if (window.MathJax && MathJax.Hub) {
            MathJax.Hub.Queue(
              ["setRenderer", MathJax.Hub, "SVG"],
              ["Rerender", MathJax.Hub]
            );
          } else {
            window.setTimeout(useMathJaxSVG, 50);
          }
        })();
        </script>
---




## Surface Area and Weight

Class Session Goals:

- How to calulate mass with variable density
- How to work with variable force or variable distance

---


## Definition of the Definite Integral

$$
\int_a^b f(x)\,dx
=
\lim_{n\to\infty}
\sum_{i=1}^{n} f(x_i^*)\,\Delta x
$$

where $f(x_i^*)\Delta x$ gives an approximation of a small "piece".

It can be a small piece of area, volume, mass, or work.

## Density of Circular Objects

Now consider a thin two-dimensional disk of radius $r$.

Density here is measured as mass per unit area. Suppose the density depends only on the distance from the center.

This is called **radial density**, $\rho(x)$.  Then $\text{mass}=\rho \cdot \text{area}$.

Because all points the same distance $x$ from the center have the same density, we divide the disk into thin circular washers.

---

## Density Approximation of a Circular Object

Consider a washer between radii $x_{i-1}$ and $x_i$.

Its area is

$$
\begin{aligned}
A_i
&=\pi x_i^2-\pi x_{i-1}^2
\end{aligned}
$$

Using $x_i^*\approx\dfrac{x_i+x_{i-1}}{2}$, we get $A_i\approx2\pi x_i^*\Delta x$.

Therefore the mass of the washer is approximately

$$
m_i
\approx
2\pi x_i^*\rho(x_i^*)\Delta x.
$$

---

## Approximating Mass

Adding all the washers,

$\text{mass}\approx
\displaystyle\sum_{i=1}^n
2\pi x_i^*\rho(x_i^*)\Delta x$.

Then take the limit

$$
\begin{aligned}
\text{mass}
&=\lim_{n \rightarrow \infty} \sum_{i=1}^n 2\pi x_i^*\rho(x_i^*)\Delta x \\
&=\int^r_0 2 \pi x \rho(x)\, dx$
\end{aligned}
$$


---

## Mass-Density Formula of a Circular Object


Let $\rho(x)$ be an integrable function representing the radial density of a disk of radius $r$.

Then the mass of the disk is

$$
\text{Mass}=\int_0^r2\pi x\rho(x)\,dx
$$


---

## Mass Density Example 1


Let $\rho(x)=\sqrt{x}$ be the radial density of a disk of radius $4$.  Find the mass of this disk.

. . . 

$$
\begin{aligned}
\text{mass}
&=\int_0^4 2\pi x\rho(x)\,dx\\
&=\frac{128\pi}{5}
\end{aligned}
$$


---

## Mass Density Example 2


Let $\rho(x)=2-|x|$ the density of a thin plate as a function of $x$.  Suppost the shape is the region bounded by $f(x)= 4-x^2$ and the $x$-axis. What is the mass of this plate?

. . . 

$$
\begin{aligned}
\text{mass}
&=\int_{-2}^2 (2-|x|) (4-x^2)\,dx\\
&=\frac{40}{3}
\end{aligned}
$$


---


## Work Done by Force

When a force moves an object, we say the force does work on the object.

For a constant force, work is the product of force and distance: $W = Fd$.

For a variable force $F(x)$ moving an object from $x=a$ to $x=b$,

$W_i \approx F(x_i^*)\Delta x$

$W \approx \sum_{i=1}^n F(x_i^*)\Delta x$

Taking the limit gives

$W=\int_a^b F(x)\,dx$

---

## Hooke's Law and Spring Constant


According to Hooke’s law, the force required to compress or stretch a spring from equilibrium is

$F(x)=kx$ where $k$ is the spring constant and $k>0$.

The work done to stretch or compress the spring from $x=a$ to $x=b$ is

$W=\int_a^b kx\,dx$

---

## Spring Example 1

Suppose it takes a force of $10$ N in the negative direction to compress a spring $0.2$ m from equilibrium. How much work is done to stretch the spring $0.5$ m from equilibrium?

First find $k$.  Then find work.

. . . 

$k=50$

$W=\frac{25}{4}=6.25$ J.



---


## Spring Example 2

A $1$ spring requires $10$ J to stretch the spring to $1.1$ m.  How much work would it take to stretch the sprint from $1$ to $1.2$ m?

Find $k$, then find work.

. . . 

$W=40J$


---

## Work to Pump Out a Circular Tank

Assume a cylindrical tank of radius $4$ m and height $10$ m is filled to a depth of $8$ m.

A representative layer has volume $V=\pi(4)^2\Delta x=16\pi\Delta x$.  The mass of water is about $1 \text{kg}/\text{cm}^3$

The force needed to lift each layer is $F=9800\cdot16\pi\Delta x=156{,}800\pi\Delta x$

The distance the layer must be lifted is approximately $x_i^*$.

So the work for one slice is $W_i\approx156{,}800\pi x_i^*\Delta x$

---

## Pumping Work Example

Adding the work for each layer gives

$W\approx\sum_{i=1}^n156{,}800\pi x_i^*\Delta x$

Taking the limit gives

$W=156{,}800\pi\int_2^{10}x\,dx$

$W=156{,}800\pi\left.\frac{x^2}{2}\right|_2^{10}$

$W=7{,}526{,}400\pi\approx23{,}644{,}883$

The work required to empty the tank is approximately $23{,}650{,}000$ J.





## Table of Antiderivatives: Trig

$$
\begin{aligned}
\int \sec^2 x\,dx &= \tan x+C \\
\int \csc^2 x\,dx &= -\cot x+C \\
\int \sec x\tan x\,dx &= \sec x+C \\
\int \csc x\cot x\,dx &= -\csc x+C
\end{aligned}
$$

---

## Table of Antiderivatives: Trig

$$
\begin{aligned}
\int \tan x\,dx &= \ln|\sec x|+C \\
\int \cot x\,dx &= \ln|\sin x|+C \\
\int \sec x\,dx &= \ln|\sec x+\tan x|+C \\
\int \csc x\,dx &= -\ln|\csc x+\cot x|+C
\end{aligned}
$$

---

## Table of Antiderivatives: Other

$$
\begin{aligned}
\int a^x\,dx &= \frac{a^x}{\ln a}+C,\quad a>0,\ a\neq1 \\
\int \log_a x\,dx &= x\log_a x-\frac{x}{\ln a}+C,\quad a>0,\ a\neq1 \\
\int \frac{1}{a^2+x^2}\,dx &= \frac{1}{a}\tan^{-1}\left(\frac{x}{a}\right)+C
\end{aligned}
$$

---

## Table of Antiderivatives: Other

$$
\begin{aligned}
\int \frac{1}{\sqrt{a^2-x^2}}\,dx &= \sin^{-1}\left(\frac{x}{a}\right)+C \\
\int \frac{1}{x\sqrt{x^2-a^2}}\,dx &= \frac{1}{a}\sec^{-1}\left|\frac{x}{a}\right|+C \\
\int \frac{1}{x^2-a^2}\,dx &= \frac{1}{2a}\ln\left|\frac{x-a}{x+a}\right|+C
\end{aligned}
$$