---
title: "Math 151 Course Learning Targets"
format:
  html:
    toc: true
    math: mathjax
  pdf: default
---


# Math 151 Course Learning Targets

To successfully learn the Calculus, you need to demonstrate that you understand some of the following Learning Targets. See @sec-grading-targets below, for what 'some' means. these learning targets are divided into five groups that represent different core principles in the course. They are:

- **A**: Applications of integration  
- **I**: Fundamental Concepts and Techniques in Integration
- **N**: Numerican Integration
- **S**: Sequences and Series
- **P**: Power Series 

Each of these groups are described in detail below. Learning Targets whose abbreviations are marked with a $\bigstar$ are Supplemental Learning Targets. The Learning Targets with an 'MP' in their abbreviation are Mathematical Practice Learning Targets. The rest are Core Learning Targets. Your grade in the course will be calcualted, primarily, from the number and type of learning targets you master.


## (A) Applications of integration

Newton and Leibniz are immortal because the mathematics they discovered (i.e., the Calculus) can be used to tell us so much about the world. In this section, we learn how to use the concept of the definite integral to create formulas that tell us other things. Just like using the sum or rectangular areas to approximate the area under a curve, all derivations use the 'cut-up-and-add-up' approach that starts with approximating the phenomena under investigation and then pass to a limit to get a definite integral. The student needs to know how to do derive some such definite integral formulas and needs to know how to use many others. We also flirt with infinity for the first time by learning about improper integrals. 

**A1**: Substitution and Integration Rules

- I know how to use the technique of u-substitution to re-write an indefinite integral in a way that allows me to compute the antiderivative of the integrand.
- I know how to use the technique of u-substitution to re-write a a definite integral an update its limits of integration in a way that allows me to compute the value of the definite integral.
- I know and can apply the integration rules for the following functions: polynomial, exponential, logarithmic, trigonometric, and inverse trigonometric functions.

**A2**: The Average Value of a Continuous Function, Area between Curves

- I know the integral formula for average value of a continuous function.
- I understand how the integral formula can be derived.
- I can apply the average value formula in a word problem.

**A3**: Volume of solids defined in terms of the shape of their cross sections.

- I understand how to read a shape described in terms of its cross-sections.
- I know how to to express the area of a cross-section as a function of the location of the cross-section (i.e., the value x).
- I know how the volume of the solid is the definite integral of the cross-sectional areas, and I know how to set the limits of that definite integral.
- I am familiar with Cavalierri's Principle and how it describes the relationship between volume and cross-sectional area.

**A4** $\bigstar$  Volumes of solids of revolution.

- I understand how to create a solid of revolution by rotating a region between an axis and a curve around the axis of rotation.
- I can draw a solid of revolution and a cross-section of that solid.
- I can find a formula for the circular cross section of the solid in terms of the location of the cross-section (i.e., the value x)
- I can write the volume of the solid of revolution as a definite integral of the area of the cross-sections, and I know how to set the limits of that definite integral.
- I can apply the above ideas to the situation where our region in bounded by two curves and rotated about an axis that does not intersect that region. (And I know why this is called the washer method.)

**A5** $\bigstar$ : Arc-length and surface area of a solid of revolution

- I understand how to apply the 'cut-up-and-add-up' principle to approximate tarc length.
-  I understand how to apply the 'cut-up-and-add-up' principle to approximate the surface area of a solid of revolution using frustrums.
- I know how and why the Mean Value Theorem is used in the derivation of the integral formula for arc length.
- I know the integral formula for the length of the graph of $y = f (x)$.
- I understand why arc length integrals are likely to need numerical methods to compute.
- I can use the integral formula to calculate surface areas of revolution, by hand and with computer.


**A6** $\bigstar$ : Calculating work done by a variable force.

- I understand how to apply the 'cut-up-and-add-up' principle to approximate the total work done in an experiment.
- I understand the role that approximating a continuous function by locally constant functions plays in the derivation of the definite integral formula.
- I can use the integral formula to calculate examples.

**A7** $\bigstar$ : Calculating the centroid of a planar region.

- I can calculate the principle of symmstry to find the centroid of a symmetric region (e.g., circle, oval, rectangle).
- I know how to use the Archimedian Principle to calculate the balance point of a finite set of point masses.
- I know how to approximate the centroid of a region between the x-axis and the graph of y = $f (x)$ using the cut-up-and-add-up method.
- I know the integral formulas for the x- and y-coordinates of the centroid of a region between the $x$-axis and the graph of $y = f (x)$.
- I could extend these formulas to integral formulas for the centroid of a threedimensional solid.

## (I) Fundamental Concepts and Techniques in Integration

We can't let computer algebra systems, like SageMath, have all the fun. We need to learn how to leverage our knowledge of algebra (e.g., completing the square) and trigonometry (e.g., Pythagorean identities, differentiation formulas) in service of antidifferentiation. In this section of the course, we learn some fundamental techniques for integration. Together the techniques allow us to antidifferentiate any rational function.

**I1**: Integration by parts in indefinite and definite integrals.
- I know how to execute the technique we call integration by parts.
- I know what the mnemonic LIATE means and how it guides the choice of functions in integration by parts.
- I know how to use integration by parts in the context of a definite integral.

**I2**: Integration using trigonometric substitutions and identities

- I can recognize when an integrand consists of combinations of trigonometric functions.
- I know how to choose a trigonometric identity to simplify expressions.
- I can use trigonometric identities to simplify expressions for the purpose of antidifferentiation.
- I know how to adjust limits of integration when using a trigonometric identity.
- I know how to use a computer to check the antiderivative (e.g., through graphing) and to check the value of an antiderivative. 

 **I3**: Improper integrals.

- I can recognize an improper integral that involves an infinite limit of integration, and I know how to rewrite it using a limit.
- I can recognize an improper integral that involves an unbounded integrand, and I know how to rewrite it using a limit. 
- I understand what it means for an improper integral to converge or diverge.
- I know the p-test for improper integrals and how the value of p for convergence depends on the type of improper integral.
- I can use the comparison test for improper integrals to determine convergence and divergence.
- I can recognize and work with the case that our improper integral requries a multiple limits.

 **I4** $\bigstar$ : Integrating rational functions using the technique of partial fraction decomposition.

- I know the pattern used to establish a partial fraction decomposition of a rational function. Specifically, 2 I understand how the multiplicity of a denominator's factors effect the decomposition and the expressions that appear in the numerators, and 2 I understand how the degree of a denominator's factors effects the decomposition (e.g., linear or irreducible quadratic).
- I understand how to find the unknown parameters in a partial fraction decompoisiton in one of two ways: equating coefficients, sampling values.
- I can use a computer algebra system (e.g., wolfram Alpha) to calculate a patial fraction decomposition.
- I can calcualte a definite integral using partial fractions decomposition.
- I can use a computer to check the result of using partial fraction decomposition to evaluate a (definite or indefinite) integral.
- I understand how partial fraction decomposition naturally leads (in some cases) to use u-substitution or trigonometric substituion. 



## (N) What do we do when we can't compute an antiderivative?

When we can't use the Fundamental Theorem of Calculus to calculate definite integral of a function, we use numerial methods.

**N1**: What it means for definite integral of continuous integrand on a closed interval to be approximated by a numerical method.
 
- I can recognize problematic integrands (i.e., those which do not have an antiderivative that can be expressed in terms of elementary functions).
- I understand that numerical integration will always give an approximate answer.
- I understand what error is in the context of numerical integration.
- I know the left and right endpoint methods for numerical approximation of a definite 2 I know the midpoint, trapezoid, and Simpson's methods for numerical approximation.

**N2**: Bounded functions and bounding error in numerical methods.

- I know why a continuous function on a closed and bounded set has an upper and lower 2 I can find a bound for a differentiable function using differentiation.
- I can find a bound for a function using a process of successive approximation. 
- I know how to find the error bound formulas for the numerical integration methods: 2 I know how to use the error bound formulas to determine the minimum number of

## (S) Sequences and Series

Sequences and series of real numbers are important objects in mathematics, and we will study their properties including how to determine whether they converge or diverge. 

 **S1**: Sequences of real numbers.

- I understand sequence notation, terms, index, notation, and visualizing (as sampling of a function, as points on real line).
- I have an understanding of the basic types of sequences (explicit, recursive), and I can recognize and translate between formula and terms.
- I can recognize when a sequence is bounded.
- I can compute the limit of a sequence for various tyles of sequences.
- I know how to apply the Algebraic Limit Theorems for sequences, the Squeeze Theorem for sequences, and the Monotone Convergence Theorem. 

**S2**: Series of real numbers.

- I understand how to use sigma notation, what a summand is, what limits of summation are, what the terms of a series are, and what a sequence of partial sums is.
- I know what it means for a series to converge, and I know what it means for a series to diverge.
- I have an understanding of the basic types of series, including telescoping series, arithmetic series, geometric series, positive series, harmonic series, and alternating series.
- I know the First Test for Convergence.
- I understand and can use the algebraic properties of convergent series including the Sum and Difference theorem for convergent series, the Constant Multiple theorem for convergent series. 

**S3**: Convergence tests

- I understand and can use the convegent tests for positive series include the Integral Test Theorem, the Direct Comparison Test Theorem, the Limit Comparison Test Theorem.
- I know how negative terms and positive terms combine to effect the convergence of a series.
- I understand what absolute convergence tells us about convergence of a series, and I know how to use tests for absolute convergence including the Ratio Test and the Root Test.
- I can explain why the alternating harmonic series is convergent but not absolutely convergent.
- I know how to estimate the sum of a convergent alternating series.

## (P) Power Series

We will apply the principles learned in our study of sequences and series of real numbers to understand sequences and series of polynomials and how polynomials can be used to approximate transcendental functions. 
 
**P1**: Power series 

- I know how to work with (do algebra on) a power series as an abstract, symbolic 'infinte' polynomial.
- I know how to view a power series as a function of an independent variable.
- I know to determine the interval of convergence of a power series, and I know how to determine if the power series converges at the endpoints of this interval.
- I know when two power series can be combined algebraically and how to create those combinations.
- I know how to apply techniques from the Calculus to power series. 

**P2** $\bigstar$ : Taylor series, Maclaurin series, and approximations.

- I know what a Taylor Series is. I know what a Maclaurin series is.
- Given an infintely differentiable function f (x) and a real number $x_0$ , I can compute the coefficients to get the associated Maclaurin Series and Taylor Series.
- I know the Taylor and Maclurin Series for the sine, the cosine, the natural logarithm, and the natural exponential function.
- I know when a function has a power series representation. 
- I can use a power series to calculate an antiderivative of functions and find approximate values of definite integrals.
- I know the error bound theorem for power series and how to use it. 

