---
title: "Math 151 Grading"
format:
  html:
    toc: true
    math: mathjax
  pdf: default
---

# Math 151 Specification Grading


This course uses specification grading, which may be new to you. Your grade in this course will reflect the degree to which you have mastered course material. You will provide me evidence that you have mastered material through work you provide on Learning Target Quizzes, oral interviews with me on Zoom, and other written assignments. This document describe the course grading structure and how your learning will be assessed.


## Course Learning Targets

To successfully learn the Calculus, you need to demonstrate that you understand some of the following Learning Area. See @sec-grading-targets below, for what 'some' means. these learning targets are divided into five groups that represent different core principles in the course. They are:

- **A**: Applications of integration  
- **I**: Fundamental Concepts and Techniques in Integration
- **N**: Numerican Integration
- **S**: Sequences and Series
- **P**: Power Series 

Each of these groups are described in detail below. Learning Targets whose abbreviations are marked with a $\bigstar$ are Supplemental Learning Targets. The Learning Targets with an 'MP' in their abbreviation are Mathematical Practice Learning Targets. The rest are Core Learning Targets. Your grade in the course will be calcualted, primarily, from the number and type of learning targets you master.


### (A) Applications of integration

Newton and Leibniz are immortal because the mathematics they discovered (i.e., the Calculus) can be used to tell us so much about the world. In this section, we learn how to use the concept of the definite integral to create formulas that tell us other things. Just like using the sum or rectangular areas to approximate the area under a curve, all derivations use the 'cut-up-and-add-up' approach that starts with approximating the phenomena under investigation and then pass to a limit to get a definite integral. The student needs to know how to do derive some such definite integral formulas and needs to know how to use many others. We also flirt with infinity for the first time by learning about improper integrals. 

**A1**: Substitution and Integration Rules
**A2**: The Average Value of a Continuous Function and Area between Curves
**A3**: Volume of solids defined in terms of the shape of their cross sections
**A4** $\bigstar$ : Volumes of solids of revolution
**A5** $\bigstar$ : Arc-length and Surface area of revolution
**A6** $\bigstar$ : Calculating work done by a variable force.
**A7** $\bigstar$ : Calculating the centroid of a planar region.

### (I) Fundamental Concepts and Techniques in Integration

We can't let computer algebra systems, like SageMath, have all the fun. We need to learn how to leverage our knowledge of algebra (e.g., completing the square) and trigonometry (e.g., Pythagorean identities, differentiation formulas) in service of antidifferentiation. In this section of the course, we learn some fundamental techniques for integration. Together the techniques allow us to antidifferentiate any rational function.

**I1**: Integration by parts
**I2**: Integration using trigonometric substitutions and identities
**I3**: Improper integrals
**I4** $\bigstar$ : Integrating rational functions using the technique of partial fraction decomposition.

### (N) What do we do when we can't compute an antiderivative?

When we can't use the Fundamental Theorem of Calculus to calculate definite integral of a function, we use numerial methods.

**N1**: What it means for definite integral of continuous integrand on a closed interval to be approximated by a numerical method.
**N2**: Bounded functions and bounding errors

### (S) Sequences and Series

Sequences and series of real numbers are important objects in mathematics, and we will study their properties including how to determine whether they converge or diverge. 

**S1**: Sequences of real numbers.
**S2**: Series of real numbers.
**S3**: Convergence tests

### (P) Power Series

We will apply the principles learned in our study of sequences and series of real numbers to understand sequences and series of polynomials and how polynomials can be used to approximate transcendental functions. 
 
**P1**: Power series 
**P2** $\bigstar$ : Taylor series, Maclaurin series, and approximations.


## Homework and Attendence

There will be weekly homework assignments. Homework assignments are submitted via CI Learn be graded for completion.  Attendance will be taken at the beginning of each class. You are expected to attend class and participate in class discussions. If you miss a class, it is your responsibility to get notes from a classmate and to ask questions about anything you do not understand.  Homework and attendance scores will be used to determine if a + or - is warrented on your final course grade.  If you submit at least 90% of the homework assignments and attend at least 90% of the classes, you will earn a + on your final course grade. If you submit less than 70% of the homework assignments or attend less than 70% of the classes, you will earn a - on your final course grade.

## Demonstrating Mastery

Every other week, a Learning Target Quizzes will be administered in class. Your work on those quizzes will be the evidence I use to decide if you've mastered the concepts and techniques of that Learning Target.

On Thursday, of week 3, 5, 7, 9 ,11, and 13, I will dedicate 1 hour of class to take a Learning Target Quiz during class time. I expect you to be prepared to take a quiz at that time.
This is how the quiz process works.

When you take a quiz, I expect you not to use any resources other than those that are in your mind and memory. With the exception of the quizzed over Numerical Integration (which require a computer tool to assist with complex calcualtions), you may not use notes or other resources, written or online, when taking a quiz.
When I assess your work, I will give you written comments. I do not award points for quizzes. Instead I will assess your work based on the evidence it provides me that you have learned the material on the quiz. I convey my assessment using an ESPN score: 

- **E**: Excellent evidence of mastery
- **S**: Sufficient evidence of mastery
- **P**: Evidence of progress toward mastery
- **N**: No evidence of understanding 

Work on a Learning Target Quiz earns an 'E' if I think I could share with the class as exemplary and worthy of emulation by other students. Work on a Learning Target Quiz earns an 'S' if I think your work is evidence of your mastery of the material. Both marks allow you to move on to the next learning target. If on a Learning Target Quiz some work is at mastery level but other work shows there are enough ideas or techniques you have not mastered, the quiz will earn an 'P'. A student will need to retake that quiz to demonstrate mastery. If you qui shows no evidence of learning, the quiz will be marked with an 'N'.

Whenever someone turns in a quiz, there is a chance that I will ask them to explain one or more answer in a face-to-face appointment. This is one way I incorporates oral quizzes into the course. What if you earn a 'P' or an 'N' on a quiz? You can retake it provided you take steps to solidify your knowledge of the material in the learning target. At minimum, you need to do the following.

1. Quiz corrections. On separate paper, write up a correct solution to each problem you missed. Your solution must be absolutely correct and clear. You are welcome to consult with your instructor before turning your corrections in.

2. Learning reflections. Include as part of your quiz corrections a short reflective statement (50-250 words) on the gaps in understanding the quiz helped you identify and what you did to solidify your understanding of the learning target. Your reflection should include at least one affirmative and detailed statement of your new understanding. For example, if your solution to a question on using u-substitution to calculate a definite integral was incorrect, your reflection might say, "It is now clear to me that when using u-substitution to calculate a definite integral, I should update the limits of integration to reflect new values associated with my new variable." 

3.  If you earned an 'N' on the quiz, you must do the above. In addition, for each question on the quiz that you did not do correctly, you must find a similar problem in the textbook (give its number and the page number on which it appears) and solve it. This question and solution should be included with your quiz corrections.     The solution for each 'additional problem' should appear immediately after the corrected solution to the quiz problem that it resembles. 

As soon as you complete the above and I do a quick review, you may retake the quiz.



## Grading {#sec-grading-targets}

This is a graded course. At the end of the semester, you will get a letter grade that will contribute to your college grade point average (GPA). I will be very clear about what it takes to earn each possible passing letter grade. Campus policy (Senate Policy SP.12.007) establishes the following interpretations for letter grades:

- **A**: Student performance has been outstanding and indicates an exceptional degree of academic achievement in meeting learning outcomes and course requirements.
- **B**: Student performance has been at a high level and indicates solid academic achievement in meeting learning outcomes and course requirements.
- **C**: Student performance has been adequate and indicates satisfactory academic achievement in meeting learning outcomes and course requirements.
- **D**: Student performance has been less than adequate and indicates deficiencies in meeting the learning outcomes and/or course requirements. 
- **F**: Student performance has been unacceptable and indicates a failure to meet the learning outcomes and/or course requirements. 

You will demonstrate your understanding of Learning Targeets through weekly or biweekly in-class quizzes (which you may retake without penalty, see below), in-class midterm exams, and the final. These assessments will focus on Core and Supplementary Learning Targets. Your work on these assessments will be evaluated on a Satisfactory/Unsatisfactory basis and will be returned to you with comments aimed at helping your improve your understanding.

To succeed in this course, you will need to demonstrate to me that you understand a significant subset of this course's 27 Learning Targets. These learning targets consist of

 - 18 Core Learning Targets, and 
 - 6 Supplementary Learning Targets Each Learning Target is described in detail in Section 1.1, above. 
 
To pass the class you need to: 
1. Demonstrate mastery on 5 Core Learning Targets one from each of the areas A, I, N, S, and P, and
2. Complete the Final Exam with a score of S on at least 2 of the 6 final exam learning targets.

To earn an C you need to:
1. Meet the requirements for passing the class, and
2. Demonstrate mastery on at least 8 Core Learning Targets.  
3. demonstrate mastery on at least 1 Supplementary Learning Targets.

To earn an B you need to:
1. Meet the requirements for passing the class, and
2. Demonstrate mastery on at least 10 Core Learning Targets.
3. demonstrate mastery on at least 3 Supplementary Learning Targets.

To earn an A you need to:
1. Meet the requirements for passing the class, and
2. Demonstrate mastery on all 12 Core Learning Targets.
3. demonstrate mastery on at least 5 Supplementary Learning Targets.


### Final Exam

The course will have a common final. This is a final exam that is taken by all students in both sections of Calculus II. Your exam consist of 6 Learning Targets exams, one from each of the areas A, I, S, and P and two learning targets of your choice.  If you receive a score of P or N on a final exam target assessment your mastery level of that target assessment with be adjusted to reflect you final exma performance.