---
title: "Arc Length of Curves"

format:
  revealjs:
    theme: solarized
    slide-number: true
    include-after-body:
      text: |
        <script>
        (function useMathJaxSVG() {
          if (window.MathJax && MathJax.Hub) {
            MathJax.Hub.Queue(
              ["setRenderer", MathJax.Hub, "SVG"],
              ["Rerender", MathJax.Hub]
            );
          } else {
            window.setTimeout(useMathJaxSVG, 50);
          }
        })();
        </script>
---




## Arc Length


Class Session Goals:


- Develop a method for calculating the arc length of a curve
- Calculate Arc Lenghts

---



## Core Idea of Chapter 2

**Integration gives us a way to add up infinitely small slices**

Defintion of the Definite Integral:
$$
\int_a^b f(x)\,dx
=
\lim_{n\to\infty}\sum_{i=1}^{n} f(x_i^*)\,\Delta x
$$

---



 

## What is Arc Length?

Arc length is the distance you would travel if you were walking along the path of the curve.

For example the cables of a suspension bridge have a certain length.  Engineers need to know how much cable will be used in their designed.

Particals moving through field sweep out a curve.  Physicist need to knwo the distance traveled.

---

## Approximating Arc Length

Let $f(x)$ be a smooth function defined over $[a,b]$.

For $i=0,1,2,\ldots,n$, let $P=\{x_0, x_1, x_2, \cdots, x_n\}$ be a regular partition of $[a,b]$.

For $i=1,2,\ldots,n$, construct a line segment from the point $(x_{i-1},f(x_{i-1}))$ to the point $(x_i,f(x_i))$.

$$
\sum_{i=1}^{n} \sqrt{(x_{i}-x_{i-1})^2 + (f(x_{i})-f(x_{i-1}))^2}
$$

---

## Recall the Mean Value Theorem

Let $f$ be continuous over the closed interval $[a,b]$ and differentiable over the open interval $(a,b)$.

Then, there exists at least one point $c \in (a,b)$ such that

$$f'(c)=\frac{f(b)-f(a)}{b-a}.$$

---

## Derivation of Arc Length Formula

By the Pythagorean theorem, the length of the line segment is

$$\sqrt{(\Delta x)^2+(\Delta y_i)^2}.$$


By the Mean Value Theorem, there is a point $x_i^*$ in $[x_{i-1},x_i]$ such that

$$f'(x_i^*)=\frac{\Delta y_i}{\Delta x}$$

---

## Theorem 2.4 Arc Length for $y=f(x)$

Let $f(x)$ be a differentiable function over the interval $[a,b]$.

Then the arc length of the portion of the graph of $f(x)$ from the point $(a,f(a))$ to the point $(b,f(b))$ is given by

$$
\text{Arc Length}=\int_a^b \sqrt{1+[f'(x)]^2}\,dx
$$

---

## Arc Length Example 1

$f(x)=\frac{4}{3}x^{3/2}$ from $x=0$ to $x=1$

[Open in Desmos](https://www.desmos.com/calculator/48wlbs2nmb){target="_blank"}

. . . 

$f'(x)=2x^{1/2}$, so $[f'(x)]^2=4x$.

. . . 

$$\text{Arc Length}=\int_0^1\sqrt{1+4x}\,dx$$


. . . 

$$=\frac{1}{6}(5\sqrt{5}-1)$$

---



## Arc Length Example 2

$f(x)=\frac{x^3}{3}+\frac{1}{4x}$ on $[1, 3]$

[Open in Desmos](https://www.desmos.com/calculator/fehwjyyhzk){target="_blank"}

. . . 

$f'(x)=x^2-\frac{1}{4x^2}$

. . . 

$=\int_1^3\sqrt{1+\left(x^2-\frac{1}{4x^2}\right)^2}\,dx$

. . . 

$=\int_1^3\left(x^2+\frac{1}{4x^2}\right)\,dx$

. . . 

$=\frac{53}{6}$

---

## Theorem 2.5 Arc Length for $x=g(y)$

Let $g(y)$ be a smooth function over a $y$ interval $[c,d]$.

Then, the arc length of the graph of $g(y)$ from the point $(g(d),d)$ to the point $(g(c),c)$ is given by

$$
\text{Arc Length}=\int_c^d \sqrt{1+[g'(y)]^2}\,dy
$$

---



## Arc Length Example 3

$g(y)=\frac{1}{y}$ on the interval $[1,4]$.

[Open in Desmos](https://www.desmos.com/calculator/q5fcf5jwyp){target="_blank"}

. . . 

$g'(y)=-\frac{1}{y^2}$, so $[g'(y)]^2=\frac{1}{y^4}$.


. . . 

$$\text{Arc Length}=\int_1^4\sqrt{1+\frac{1}{y^4}}\,dy$$

. . . 

What to do next?

[Open in Desmos](https://www.desmos.com/calculator/gzkjxpxl33){target="_blank"}

---

## Note about Numerical Integration

Although it is nice to have a formula for calculating arc length, this particular theorem can generate expressions that are difficult to integrate.

In some cases, we may have to use a computer or calculator to approximate the value of the integral.

We can go back to the formula we started with:

$$
\sum_{i=1}^{n} \sqrt{(x_{i}-x_{i-1})^2 + (f(x_{i})-f(x_{i-1}))^2}
$$

and choose the appropriate $n$.

---

## Table of Antiderivatives: Trig

$$
\begin{aligned}
\int \sec^2 x\,dx &= \tan x+C \\
\int \csc^2 x\,dx &= -\cot x+C \\
\int \sec x\tan x\,dx &= \sec x+C \\
\int \csc x\cot x\,dx &= -\csc x+C
\end{aligned}
$$

---

## Table of Antiderivatives: Trig

$$
\begin{aligned}
\int \tan x\,dx &= \ln|\sec x|+C \\
\int \cot x\,dx &= \ln|\sin x|+C \\
\int \sec x\,dx &= \ln|\sec x+\tan x|+C \\
\int \csc x\,dx &= -\ln|\csc x+\cot x|+C
\end{aligned}
$$

---

## Table of Antiderivatives: Other

$$
\begin{aligned}
\int a^x\,dx &= \frac{a^x}{\ln a}+C,\quad a>0,\ a\neq1 \\
\int \log_a x\,dx &= x\log_a x-\frac{x}{\ln a}+C,\quad a>0,\ a\neq1 \\
\int \frac{1}{a^2+x^2}\,dx &= \frac{1}{a}\tan^{-1}\left(\frac{x}{a}\right)+C
\end{aligned}
$$

---

## Table of Antiderivatives: Other

$$
\begin{aligned}
\int \frac{1}{\sqrt{a^2-x^2}}\,dx &= \sin^{-1}\left(\frac{x}{a}\right)+C \\
\int \frac{1}{x\sqrt{x^2-a^2}}\,dx &= \frac{1}{a}\sec^{-1}\left|\frac{x}{a}\right|+C \\
\int \frac{1}{x^2-a^2}\,dx &= \frac{1}{2a}\ln\left|\frac{x-a}{x+a}\right|+C
\end{aligned}
$$