---
title: "Surface Area and Mass"

format:
  revealjs:
    theme: solarized
    slide-number: true
    include-after-body:
      text: |
        <script>
        (function useMathJaxSVG() {
          if (window.MathJax && MathJax.Hub) {
            MathJax.Hub.Queue(
              ["setRenderer", MathJax.Hub, "SVG"],
              ["Rerender", MathJax.Hub]
            );
          } else {
            window.setTimeout(useMathJaxSVG, 50);
          }
        })();
        </script>
---




## Surface Area and Weight

Class Session Goals:

- Approximate the surface area of a solid of revolution using frustums.
- Calculate the surface area of a solid of revolution using integration.
- Use density functions to calculate the mass of one-dimensional objects.
- Use radial density functions to calculate the mass of circular objects.

---


## Core Idea of Chapter 2

**Integration gives us a way to add up infinitely small pieces.**

Definition of the Definite Integral:

$$
\int_a^b f(x)\,dx
=
\lim_{n\to\infty}
\sum_{i=1}^{n} f(x_i^*)\,\Delta x
$$

where $f(x_i^*)\Delta x$ gives the approximate contribution from one small piece, in this case area. The same basic idea can be used to calculate: volumes, mass from density, and work from force.


---

## Surface Area of a Cone

The lateral surface area, excluding the base, of a cone is

$$
\text{Surface Area}=\pi r s
$$

where $r$ is the radius of the base and $s$ is the slant height.

For a right circular cone, $s=\sqrt{r^2+h^2}$, so the total surface area is

$$
$\text{Surface Area}=\pi r\sqrt{r^2+h^2}
$$

---


## What is a Frustum?

A **frustum of a cone** is the portion of a cone that remains after the pointed end has been cut off.

For a frustum, let

- $r$ = radius of the wide end,
- $R$ = radius of the narrow end,
- $l$ = slant height.

We are interested in the **surface area** of this broken off piece of a cone. Frustrum comes from the a latin word meaning "broken off piece".  The plural of frustrum is frustra, kinda of like the plural of minimum is minima.


---


## Surface Area of a Frustum


Using similar triangles and subtracting the smaller cone from the larger cone gives the lateral surface area of a frustum (derivation of this formult in in the book):

$$
S=\pi(R+r)s
$$


$\dfrac{R+r}{2}$ is the **average radius** of the frustum. So we can rewrite this as $S=(2\pi\text{ average radius})(\text{slant height})$.

---


## Approximating Surface Area of Revolution

Let $f(x)$ be a nonnegative smooth function on $[a,b]$.

We want the surface area generated by revolving $y=f(x)$ around the $x$-axis.

1. Partition $[a,b]$ into small intervals.
2. Approximate the curve on each interval by a **line segment**.
3. Revolve each line segment around the $x$-axis.

Each line segment generates a small band that is a frustrum.


---

## Formula for the Approximation of Surface Area Using Frusta

For the $i$th interval, the radii are

$r_1=f(x_{i-1})$ and $r_2=f(x_i)$.

The slant height is

$l=\sqrt{(\Delta x)^2+(\Delta y)^2}$.

---

## Formula for the Approximation of Surface Area Using Frusta

$S_i=\pi\left(f(x_{i-1})+f(x_i)\right)
\sqrt{(\Delta x)^2+(\Delta y)^2}$.

Using the Mean Value Theorem, $\dfrac{\Delta y}{\Delta x}=f'(x_i^*)$, and using $f(x_i^{**})$ for the average radius, the surface area of the $i^{\text{th}}$ frustrum is:

$$
S_i
=
2\pi f(x_i^{**})\Delta x
\sqrt{1+\left(f'(x_i^*)\right)^2}.
$$


---

## Addding up the surface area of the frustra

$$
\text{Surface Area}\approx
\displaystyle\sum_{i=1}^n
2\pi f(x_i^{**})
\sqrt{1+\left(f'(x_i^*)\right)^2}\Delta x
$$

Let the number of partitions go to infinity.

---

## Theorem 2.6 Surface Area of Revolution


Let $f(x)$ be a nonnegative smooth function over $[a,b]$.

If the graph of $f(x)$ is revolved around the $x$-axis, then

$$
\begin{aligned}
\text{Surface Area}
&= \lim_{n \rightarrow \infty} \\[0.5em]
&\quad \sum_{i=1}^n 2\pi f(x_i^*)
\sqrt{1+\left(f'(x_i^*)\right)^2}\Delta x \\[0.5em]
&= \int_a^b 2\pi f(x)
\sqrt{1+\left[f'(x)\right]^2}\,dx
\end{aligned}
$$

## Theorem 2.6 Surface Area of Revolution around $y$-axis

If $x=g(y)$ is revolved around the $y$-axis,

$$
\text{Surface Area}
=
\int_c^d
2\pi g(y)
\sqrt{1+\left[g'(y)\right]^2}\,dy
$$

---

## Surface Area Example 1


Let $f(x)=\sqrt{x}$ on $[1,4]$.

Find the surface area generated by revolving the graph around the $x$-axis.

. . . 

$f'(x)=\dfrac{1}{2\sqrt{x}}$

. . . 

$$
\begin{aligned}
\text{Surface Area}
&=\int_1^4
2\pi\sqrt{x}
\sqrt{1+\frac{1}{4x}}\,dx\\
&=\int_1^4
2\pi\sqrt{x+\frac14}\,dx.
\end{aligned}
$$

. . .
$$
\boxed{
\text{Surface Area}
=
\frac{\pi}{6}
\left(17\sqrt{17}-5\sqrt5\right)
}
$$

---

## Surface Area Example 2


Let $y=\sqrt[3]{3x}$, for $0\le y\le2$, and revolve the curve around the $y$-axis.

. . . 

Rewrite the curve as a function of $y$: $x=g(y)=\dfrac13y^3$.

. . . 

$g'(y)=y^2$.

Thus,

$$
\begin{aligned}
\text{Surface Area}
&=\int_0^2
2\pi\left(\frac13y^3\right)
\sqrt{1+y^4}\,dy\\
&=\frac{2\pi}{3}
\int_0^2 y^3\sqrt{1+y^4}\,dy.
\end{aligned}
$$

. . . 

$$
\boxed{
\text{Surface Area}
=
\frac{\pi}{9}
\left(17^{3/2}-1\right)
}
$$

---

## Density of the air above sea level as a function of height

A common approximation of the density of air is $\rho(h)=\rho e^{-h/H}$ where:

- $\rho \approx 1.225\ \mathrm{kg/m^3}$ is sea-level air density
- $h$ is altitude above sea level in meters
- $H \approx 8500\ \mathrm{m}$ and is upper limit for accuracy of this model

---



## What is the mass of air above 1 square meter?

For a column of air with base area $1\ \mathrm{m^2}$,

$$m=\int_0^{/infty} \rho_0 e^{-h/H}\,dh=\rho_0H$$

So,

$$m\approx (1.225)(8500)=10412.5\ \mathrm{kg}$$

Thus, the mass of air above $1\ \mathrm{m^2}$ is approximately $1.04\times 10^4\ \mathrm{kg}$.


---

## Relating the mass of air to pressure at sea level

Pressure is force per unit area: $P=\frac{F}{A}$.

For a $1\ \mathrm{m^2}$ column of air, $F=mg$, so

$$P=\rho_0Hg$$

Using $\rho_0 \approx 1.225\ \mathrm{kg/m^3}$, $H\approx 8500\ \mathrm{m}$, and $g\approx 9.81\ \mathrm{m/s^2}$,

$$P\approx (1.225)(8500)(9.81)=1.02\times 10^5\ \mathrm{Pa}$$

This is very close to standard atmospheric pressure at sea level: $101{,}325\ \mathrm{Pa}$.

---


## Density Functions

Density describes how **mass is distributed** throughout an object.

For a one-dimensional object such as a thin rod:

$\rho(x)=$ mass per unit length.

If the density is constant,

$m=(\text{density})(\text{length})$.

Thus,

$m=\rho(b-a)$.

If density varies with position, we use a **linear density function**

$\rho(x)$.

Integration allows us to add the masses of infinitely small pieces of the rod.

---

## Density Approximations of a 1-Dimensional Object

Consider a thin rod extending from $x=a$ to $x=b$.

Partition the rod into small pieces of length $\Delta x$.

On the $i$th piece, choose

$x_i^*\in[x_{i-1},x_i]$.

The density of this small piece is approximately constant:

$\rho(x)\approx\rho(x_i^*)$.

Therefore its mass is approximately

$$
m_i\approx\rho(x_i^*)\Delta x.
$$

Adding the masses,

$$
\text{Mass}\approx
\sum_{i=1}^n
\rho(x_i^*)\Delta x.
$$


---

## Theorem 2.7 Mass-Density Formula for One-Dimensional Objects

**Mass–Density Formula of a One-Dimensional Object**

Given a thin rod oriented along the $x$-axis over $[a,b]$, let $\rho(x)$ denote a linear density function.

Then the mass of the rod is

$$
\text{Mass}=\int_a^b\rho(x)\,dx
$$


---

##  Example Mass Desinity of a Thin Rod


Consider a thin rod on the $x$-axis over $\left[\dfrac{\pi}{2},\pi\right]$.

Suppose its density is $\rho(x)=\sin x$. The mass is

$$
\begin{aligned}
m
&=\int_{\pi/2}^{\pi}\rho(x)\,dx\\
&=\int_{\pi/2}^{\pi}\sin x\,dx\\
&=\left.-\cos x\right|_{\pi/2}^{\pi}\\
&=1.
\end{aligned}
$$


---

## Density of Circular Objects

Now consider a thin two-dimensional disk of radius $r$.

Density here is measured as mass per unit area. Suppose the density depends only on the distance from the center.

This is called **radial density**, $\rho(x)$.

Because all points the same distance $x$ from the center have the same density, we divide the disk into thin circular washers.

---

## Density Approximation of a Circular Object

Consider a washer between radii $x_{i-1}$ and $x_i$.

Its area is

$$
\begin{aligned}
A_i
&=\pi x_i^2-\pi x_{i-1}^2\\
&=\pi(x_i+x_{i-1})\Delta x.
\end{aligned}
$$

Using

$x_i^*\approx\dfrac{x_i+x_{i-1}}{2}$,

we obtain

$A_i\approx2\pi x_i^*\Delta x$.

Therefore the mass of the washer is approximately

$$
m_i
\approx
2\pi x_i^*\rho(x_i^*)\Delta x.
$$

Adding all the washers,

$m\approx
\displaystyle\sum_{i=1}^n
2\pi x_i^*\rho(x_i^*)\Delta x$.

---

## Theorem 2.8 Mass-Density Formula of a Circular Object


Let $\rho(x)$ be an integrable function representing the radial density of a disk of radius $r$.

Then the mass of the disk is

$$
\text{Mass}=\int_0^r2\pi x\rho(x)\,dx
$$


---

## Mass Density Example of Circular Object


Let

$\rho(x)=\sqrt{x}$

represent the radial density of a disk of radius $4$.

Using Theorem 2.8,

$$
\begin{aligned}
m
&=\int_0^4 2\pi x\rho(x)\,dx\\
&=\int_0^4 2\pi x\sqrt{x}\,dx\\
&=2\pi\int_0^4x^{3/2}\,dx\\
&=2\pi\left[\frac25x^{5/2}\right]_0^4.
\end{aligned}
$$

Thus,

$$
\boxed{
m=\frac{128\pi}{5}
}
$$




## Table of Antiderivatives: Trig

$$
\begin{aligned}
\int \sec^2 x\,dx &= \tan x+C \\
\int \csc^2 x\,dx &= -\cot x+C \\
\int \sec x\tan x\,dx &= \sec x+C \\
\int \csc x\cot x\,dx &= -\csc x+C
\end{aligned}
$$

---

## Table of Antiderivatives: Trig

$$
\begin{aligned}
\int \tan x\,dx &= \ln|\sec x|+C \\
\int \cot x\,dx &= \ln|\sin x|+C \\
\int \sec x\,dx &= \ln|\sec x+\tan x|+C \\
\int \csc x\,dx &= -\ln|\csc x+\cot x|+C
\end{aligned}
$$

---

## Table of Antiderivatives: Other

$$
\begin{aligned}
\int a^x\,dx &= \frac{a^x}{\ln a}+C,\quad a>0,\ a\neq1 \\
\int \log_a x\,dx &= x\log_a x-\frac{x}{\ln a}+C,\quad a>0,\ a\neq1 \\
\int \frac{1}{a^2+x^2}\,dx &= \frac{1}{a}\tan^{-1}\left(\frac{x}{a}\right)+C
\end{aligned}
$$

---

## Table of Antiderivatives: Other

$$
\begin{aligned}
\int \frac{1}{\sqrt{a^2-x^2}}\,dx &= \sin^{-1}\left(\frac{x}{a}\right)+C \\
\int \frac{1}{x\sqrt{x^2-a^2}}\,dx &= \frac{1}{a}\sec^{-1}\left|\frac{x}{a}\right|+C \\
\int \frac{1}{x^2-a^2}\,dx &= \frac{1}{2a}\ln\left|\frac{x-a}{x+a}\right|+C
\end{aligned}
$$